version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test:unit
  analyze:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
